export type CurrentStrengthTeam = {
  rank: number;
  team_name: string;
  current_strength_score: number;
  recent_form_score: number;
  recent_goal_difference_score: number;
  host_advantage_score: number;
  matches_used: number;
  points_per_match: number;
  wins: number;
  draws: number;
  losses: number;
  goals_for: number;
  goals_against: number;
  average_goal_difference: number;
  latest_match_date: string;
  is_2026_host: 0 | 1;
};

export const currentStrengthFormula =
  "0.65 * recent_form_score + 0.25 * recent_goal_difference_score + 0.10 * host_advantage_score";

export const currentStrengthTeams = [
  {
    "rank": 1,
    "team_name": "Morocco",
    "current_strength_score": 75.5,
    "recent_form_score": 86.67,
    "recent_goal_difference_score": 76.67,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 2.6,
    "wins": 16,
    "draws": 4,
    "losses": 0,
    "goals_for": 38,
    "goals_against": 6,
    "average_goal_difference": 1.6,
    "latest_match_date": "2026-05-26",
    "is_2026_host": 0
  },
  {
    "rank": 2,
    "team_name": "Spain",
    "current_strength_score": 71.58,
    "recent_form_score": 80,
    "recent_goal_difference_score": 78.33,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 2.4,
    "wins": 14,
    "draws": 6,
    "losses": 0,
    "goals_for": 53,
    "goals_against": 19,
    "average_goal_difference": 1.7,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 3,
    "team_name": "Canada",
    "current_strength_score": 70,
    "recent_form_score": 66.67,
    "recent_goal_difference_score": 66.67,
    "host_advantage_score": 100,
    "matches_used": 20,
    "points_per_match": 2,
    "wins": 11,
    "draws": 7,
    "losses": 2,
    "goals_for": 30,
    "goals_against": 10,
    "average_goal_difference": 1,
    "latest_match_date": "2026-06-01",
    "is_2026_host": 1
  },
  {
    "rank": 4,
    "team_name": "England",
    "current_strength_score": 69.63,
    "recent_form_score": 76.67,
    "recent_goal_difference_score": 79.17,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 2.3,
    "wins": 15,
    "draws": 1,
    "losses": 4,
    "goals_for": 46,
    "goals_against": 11,
    "average_goal_difference": 1.75,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 5,
    "team_name": "Japan",
    "current_strength_score": 69.58,
    "recent_form_score": 75,
    "recent_goal_difference_score": 83.33,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 2.25,
    "wins": 14,
    "draws": 3,
    "losses": 3,
    "goals_for": 48,
    "goals_against": 8,
    "average_goal_difference": 2,
    "latest_match_date": "2026-05-31",
    "is_2026_host": 0
  },
  {
    "rank": 6,
    "team_name": "Norway",
    "current_strength_score": 69.58,
    "recent_form_score": 75,
    "recent_goal_difference_score": 83.33,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 2.25,
    "wins": 14,
    "draws": 3,
    "losses": 3,
    "goals_for": 59,
    "goals_against": 19,
    "average_goal_difference": 2,
    "latest_match_date": "2026-06-01",
    "is_2026_host": 0
  },
  {
    "rank": 7,
    "team_name": "Algeria",
    "current_strength_score": 68.79,
    "recent_form_score": 76.67,
    "recent_goal_difference_score": 75.83,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 2.3,
    "wins": 14,
    "draws": 4,
    "losses": 2,
    "goals_for": 43,
    "goals_against": 12,
    "average_goal_difference": 1.55,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 8,
    "team_name": "Russia",
    "current_strength_score": 68.5,
    "recent_form_score": 73.33,
    "recent_goal_difference_score": 83.33,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 2.2,
    "wins": 13,
    "draws": 5,
    "losses": 2,
    "goals_for": 52,
    "goals_against": 12,
    "average_goal_difference": 2,
    "latest_match_date": "2026-05-28",
    "is_2026_host": 0
  },
  {
    "rank": 9,
    "team_name": "Mexico",
    "current_strength_score": 68.34,
    "recent_form_score": 66.67,
    "recent_goal_difference_score": 60,
    "host_advantage_score": 100,
    "matches_used": 20,
    "points_per_match": 2,
    "wins": 11,
    "draws": 7,
    "losses": 2,
    "goals_for": 25,
    "goals_against": 13,
    "average_goal_difference": 0.6,
    "latest_match_date": "2026-05-30",
    "is_2026_host": 1
  },
  {
    "rank": 10,
    "team_name": "Argentina",
    "current_strength_score": 68.13,
    "recent_form_score": 75,
    "recent_goal_difference_score": 77.5,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 2.25,
    "wins": 14,
    "draws": 3,
    "losses": 3,
    "goals_for": 43,
    "goals_against": 10,
    "average_goal_difference": 1.65,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 11,
    "team_name": "Senegal",
    "current_strength_score": 67.92,
    "recent_form_score": 75,
    "recent_goal_difference_score": 76.67,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 2.25,
    "wins": 14,
    "draws": 3,
    "losses": 3,
    "goals_for": 47,
    "goals_against": 15,
    "average_goal_difference": 1.6,
    "latest_match_date": "2026-05-31",
    "is_2026_host": 0
  },
  {
    "rank": 12,
    "team_name": "Ivory Coast",
    "current_strength_score": 66.41,
    "recent_form_score": 73.33,
    "recent_goal_difference_score": 75,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 2.2,
    "wins": 14,
    "draws": 2,
    "losses": 4,
    "goals_for": 40,
    "goals_against": 10,
    "average_goal_difference": 1.5,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 13,
    "team_name": "Germany",
    "current_strength_score": 64.25,
    "recent_form_score": 70,
    "recent_goal_difference_score": 75,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 2.1,
    "wins": 13,
    "draws": 3,
    "losses": 4,
    "goals_for": 51,
    "goals_against": 21,
    "average_goal_difference": 1.5,
    "latest_match_date": "2026-05-31",
    "is_2026_host": 0
  },
  {
    "rank": 14,
    "team_name": "DR Congo",
    "current_strength_score": 63.91,
    "recent_form_score": 73.33,
    "recent_goal_difference_score": 65,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 2.2,
    "wins": 14,
    "draws": 2,
    "losses": 4,
    "goals_for": 29,
    "goals_against": 11,
    "average_goal_difference": 0.9,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 15,
    "team_name": "Iran",
    "current_strength_score": 63.21,
    "recent_form_score": 70,
    "recent_goal_difference_score": 70.83,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 2.1,
    "wins": 13,
    "draws": 3,
    "losses": 4,
    "goals_for": 43,
    "goals_against": 18,
    "average_goal_difference": 1.25,
    "latest_match_date": "2026-05-29",
    "is_2026_host": 0
  },
  {
    "rank": 16,
    "team_name": "France",
    "current_strength_score": 62.38,
    "recent_form_score": 70,
    "recent_goal_difference_score": 67.5,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 2.1,
    "wins": 13,
    "draws": 3,
    "losses": 4,
    "goals_for": 42,
    "goals_against": 21,
    "average_goal_difference": 1.05,
    "latest_match_date": "2026-03-29",
    "is_2026_host": 0
  },
  {
    "rank": 17,
    "team_name": "Austria",
    "current_strength_score": 62.09,
    "recent_form_score": 66.67,
    "recent_goal_difference_score": 75,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 2,
    "wins": 12,
    "draws": 4,
    "losses": 4,
    "goals_for": 45,
    "goals_against": 15,
    "average_goal_difference": 1.5,
    "latest_match_date": "2026-06-01",
    "is_2026_host": 0
  },
  {
    "rank": 18,
    "team_name": "Turkey",
    "current_strength_score": 61.75,
    "recent_form_score": 70,
    "recent_goal_difference_score": 65,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 2.1,
    "wins": 13,
    "draws": 3,
    "losses": 4,
    "goals_for": 41,
    "goals_against": 23,
    "average_goal_difference": 0.9,
    "latest_match_date": "2026-06-01",
    "is_2026_host": 0
  },
  {
    "rank": 19,
    "team_name": "Nigeria",
    "current_strength_score": 61.29,
    "recent_form_score": 68.33,
    "recent_goal_difference_score": 67.5,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 2.05,
    "wins": 11,
    "draws": 8,
    "losses": 1,
    "goals_for": 37,
    "goals_against": 16,
    "average_goal_difference": 1.05,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 20,
    "team_name": "Portugal",
    "current_strength_score": 61.25,
    "recent_form_score": 66.67,
    "recent_goal_difference_score": 71.67,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 2,
    "wins": 11,
    "draws": 7,
    "losses": 2,
    "goals_for": 44,
    "goals_against": 18,
    "average_goal_difference": 1.3,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 21,
    "team_name": "South Korea",
    "current_strength_score": 60.25,
    "recent_form_score": 68.33,
    "recent_goal_difference_score": 63.33,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 2.05,
    "wins": 12,
    "draws": 5,
    "losses": 3,
    "goals_for": 35,
    "goals_against": 19,
    "average_goal_difference": 0.8,
    "latest_match_date": "2026-05-30",
    "is_2026_host": 0
  },
  {
    "rank": 22,
    "team_name": "Netherlands",
    "current_strength_score": 59.91,
    "recent_form_score": 63.33,
    "recent_goal_difference_score": 75,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.9,
    "wins": 10,
    "draws": 8,
    "losses": 2,
    "goals_for": 51,
    "goals_against": 21,
    "average_goal_difference": 1.5,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 23,
    "team_name": "New Zealand",
    "current_strength_score": 59.83,
    "recent_form_score": 60,
    "recent_goal_difference_score": 83.33,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.8,
    "wins": 11,
    "draws": 3,
    "losses": 6,
    "goals_for": 55,
    "goals_against": 15,
    "average_goal_difference": 2,
    "latest_match_date": "2026-03-30",
    "is_2026_host": 0
  },
  {
    "rank": 24,
    "team_name": "Egypt",
    "current_strength_score": 58.96,
    "recent_form_score": 66.67,
    "recent_goal_difference_score": 62.5,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 2,
    "wins": 11,
    "draws": 7,
    "losses": 2,
    "goals_for": 26,
    "goals_against": 11,
    "average_goal_difference": 0.75,
    "latest_match_date": "2026-05-28",
    "is_2026_host": 0
  },
  {
    "rank": 25,
    "team_name": "Haiti",
    "current_strength_score": 58.42,
    "recent_form_score": 61.67,
    "recent_goal_difference_score": 73.33,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.85,
    "wins": 11,
    "draws": 4,
    "losses": 5,
    "goals_for": 50,
    "goals_against": 22,
    "average_goal_difference": 1.4,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 26,
    "team_name": "United States",
    "current_strength_score": 58.21,
    "recent_form_score": 53.33,
    "recent_goal_difference_score": 54.17,
    "host_advantage_score": 100,
    "matches_used": 20,
    "points_per_match": 1.6,
    "wins": 10,
    "draws": 2,
    "losses": 8,
    "goals_for": 35,
    "goals_against": 30,
    "average_goal_difference": 0.25,
    "latest_match_date": "2026-05-31",
    "is_2026_host": 1
  },
  {
    "rank": 27,
    "team_name": "Croatia",
    "current_strength_score": 58.04,
    "recent_form_score": 63.33,
    "recent_goal_difference_score": 67.5,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.9,
    "wins": 11,
    "draws": 5,
    "losses": 4,
    "goals_for": 42,
    "goals_against": 21,
    "average_goal_difference": 1.05,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 28,
    "team_name": "Australia",
    "current_strength_score": 56.96,
    "recent_form_score": 61.67,
    "recent_goal_difference_score": 67.5,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.85,
    "wins": 11,
    "draws": 4,
    "losses": 5,
    "goals_for": 36,
    "goals_against": 15,
    "average_goal_difference": 1.05,
    "latest_match_date": "2026-05-30",
    "is_2026_host": 0
  },
  {
    "rank": 29,
    "team_name": "Cameroon",
    "current_strength_score": 56.79,
    "recent_form_score": 63.33,
    "recent_goal_difference_score": 62.5,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.9,
    "wins": 11,
    "draws": 5,
    "losses": 4,
    "goals_for": 27,
    "goals_against": 12,
    "average_goal_difference": 0.75,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 30,
    "team_name": "Tunisia",
    "current_strength_score": 55.46,
    "recent_form_score": 60,
    "recent_goal_difference_score": 65.83,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.8,
    "wins": 10,
    "draws": 6,
    "losses": 4,
    "goals_for": 35,
    "goals_against": 16,
    "average_goal_difference": 0.95,
    "latest_match_date": "2026-06-01",
    "is_2026_host": 0
  },
  {
    "rank": 31,
    "team_name": "Italy",
    "current_strength_score": 55.29,
    "recent_form_score": 61.67,
    "recent_goal_difference_score": 60.83,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.85,
    "wins": 11,
    "draws": 4,
    "losses": 5,
    "goals_for": 42,
    "goals_against": 29,
    "average_goal_difference": 0.65,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 32,
    "team_name": "Uzbekistan",
    "current_strength_score": 55.29,
    "recent_form_score": 61.67,
    "recent_goal_difference_score": 60.83,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.85,
    "wins": 10,
    "draws": 7,
    "losses": 3,
    "goals_for": 28,
    "goals_against": 15,
    "average_goal_difference": 0.65,
    "latest_match_date": "2026-06-01",
    "is_2026_host": 0
  },
  {
    "rank": 33,
    "team_name": "Brazil",
    "current_strength_score": 55.25,
    "recent_form_score": 60,
    "recent_goal_difference_score": 65,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.8,
    "wins": 10,
    "draws": 6,
    "losses": 4,
    "goals_for": 35,
    "goals_against": 17,
    "average_goal_difference": 0.9,
    "latest_match_date": "2026-05-31",
    "is_2026_host": 0
  },
  {
    "rank": 34,
    "team_name": "South Africa",
    "current_strength_score": 55.25,
    "recent_form_score": 60,
    "recent_goal_difference_score": 65,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.8,
    "wins": 10,
    "draws": 6,
    "losses": 4,
    "goals_for": 33,
    "goals_against": 15,
    "average_goal_difference": 0.9,
    "latest_match_date": "2026-05-29",
    "is_2026_host": 0
  },
  {
    "rank": 35,
    "team_name": "Czech Republic",
    "current_strength_score": 54,
    "recent_form_score": 60,
    "recent_goal_difference_score": 60,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.8,
    "wins": 10,
    "draws": 6,
    "losses": 4,
    "goals_for": 36,
    "goals_against": 24,
    "average_goal_difference": 0.6,
    "latest_match_date": "2026-05-31",
    "is_2026_host": 0
  },
  {
    "rank": 36,
    "team_name": "Greece",
    "current_strength_score": 53.33,
    "recent_form_score": 58.33,
    "recent_goal_difference_score": 61.67,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.75,
    "wins": 11,
    "draws": 2,
    "losses": 7,
    "goals_for": 35,
    "goals_against": 21,
    "average_goal_difference": 0.7,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 37,
    "team_name": "Panama",
    "current_strength_score": 53.17,
    "recent_form_score": 60,
    "recent_goal_difference_score": 56.67,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.8,
    "wins": 10,
    "draws": 6,
    "losses": 4,
    "goals_for": 34,
    "goals_against": 26,
    "average_goal_difference": 0.4,
    "latest_match_date": "2026-05-31",
    "is_2026_host": 0
  },
  {
    "rank": 38,
    "team_name": "Yugoslavia",
    "current_strength_score": 52.46,
    "recent_form_score": 56.67,
    "recent_goal_difference_score": 62.5,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.7,
    "wins": 10,
    "draws": 4,
    "losses": 6,
    "goals_for": 37,
    "goals_against": 22,
    "average_goal_difference": 0.75,
    "latest_match_date": "1992-03-25",
    "is_2026_host": 0
  },
  {
    "rank": 39,
    "team_name": "Curaçao",
    "current_strength_score": 52.21,
    "recent_form_score": 55,
    "recent_goal_difference_score": 65.83,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.65,
    "wins": 9,
    "draws": 6,
    "losses": 5,
    "goals_for": 40,
    "goals_against": 21,
    "average_goal_difference": 0.95,
    "latest_match_date": "2026-05-30",
    "is_2026_host": 0
  },
  {
    "rank": 40,
    "team_name": "Denmark",
    "current_strength_score": 51.79,
    "recent_form_score": 55,
    "recent_goal_difference_score": 64.17,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.65,
    "wins": 9,
    "draws": 6,
    "losses": 5,
    "goals_for": 39,
    "goals_against": 22,
    "average_goal_difference": 0.85,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 41,
    "team_name": "Jamaica",
    "current_strength_score": 51.63,
    "recent_form_score": 56.67,
    "recent_goal_difference_score": 59.17,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.7,
    "wins": 10,
    "draws": 4,
    "losses": 6,
    "goals_for": 28,
    "goals_against": 17,
    "average_goal_difference": 0.55,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 42,
    "team_name": "Romania",
    "current_strength_score": 50.96,
    "recent_form_score": 55,
    "recent_goal_difference_score": 60.83,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.65,
    "wins": 10,
    "draws": 3,
    "losses": 7,
    "goals_for": 37,
    "goals_against": 24,
    "average_goal_difference": 0.65,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 43,
    "team_name": "German DR",
    "current_strength_score": 50.79,
    "recent_form_score": 56.67,
    "recent_goal_difference_score": 55.83,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.7,
    "wins": 10,
    "draws": 4,
    "losses": 6,
    "goals_for": 34,
    "goals_against": 27,
    "average_goal_difference": 0.35,
    "latest_match_date": "1990-09-12",
    "is_2026_host": 0
  },
  {
    "rank": 44,
    "team_name": "Sweden",
    "current_strength_score": 50.54,
    "recent_form_score": 55,
    "recent_goal_difference_score": 59.17,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.65,
    "wins": 10,
    "draws": 3,
    "losses": 7,
    "goals_for": 41,
    "goals_against": 30,
    "average_goal_difference": 0.55,
    "latest_match_date": "2026-06-01",
    "is_2026_host": 0
  },
  {
    "rank": 45,
    "team_name": "Ecuador",
    "current_strength_score": 50.33,
    "recent_form_score": 55,
    "recent_goal_difference_score": 58.33,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.65,
    "wins": 7,
    "draws": 12,
    "losses": 1,
    "goals_for": 18,
    "goals_against": 8,
    "average_goal_difference": 0.5,
    "latest_match_date": "2026-05-30",
    "is_2026_host": 0
  },
  {
    "rank": 46,
    "team_name": "Belgium",
    "current_strength_score": 49.58,
    "recent_form_score": 50,
    "recent_goal_difference_score": 68.33,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.5,
    "wins": 8,
    "draws": 6,
    "losses": 6,
    "goals_for": 45,
    "goals_against": 23,
    "average_goal_difference": 1.1,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 47,
    "team_name": "Switzerland",
    "current_strength_score": 49,
    "recent_form_score": 51.67,
    "recent_goal_difference_score": 61.67,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.55,
    "wins": 8,
    "draws": 7,
    "losses": 5,
    "goals_for": 40,
    "goals_against": 26,
    "average_goal_difference": 0.7,
    "latest_match_date": "2026-05-31",
    "is_2026_host": 0
  },
  {
    "rank": 48,
    "team_name": "Honduras",
    "current_strength_score": 48.88,
    "recent_form_score": 55,
    "recent_goal_difference_score": 52.5,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.65,
    "wins": 9,
    "draws": 6,
    "losses": 5,
    "goals_for": 25,
    "goals_against": 22,
    "average_goal_difference": 0.15,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 49,
    "team_name": "Cape Verde",
    "current_strength_score": 48.41,
    "recent_form_score": 53.33,
    "recent_goal_difference_score": 55,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.6,
    "wins": 9,
    "draws": 5,
    "losses": 6,
    "goals_for": 28,
    "goals_against": 22,
    "average_goal_difference": 0.3,
    "latest_match_date": "2026-05-31",
    "is_2026_host": 0
  },
  {
    "rank": 50,
    "team_name": "Wales",
    "current_strength_score": 47.54,
    "recent_form_score": 51.67,
    "recent_goal_difference_score": 55.83,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.55,
    "wins": 8,
    "draws": 7,
    "losses": 5,
    "goals_for": 32,
    "goals_against": 25,
    "average_goal_difference": 0.35,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 51,
    "team_name": "Republic of Ireland",
    "current_strength_score": 47.37,
    "recent_form_score": 53.33,
    "recent_goal_difference_score": 50.83,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.6,
    "wins": 9,
    "draws": 5,
    "losses": 6,
    "goals_for": 25,
    "goals_against": 24,
    "average_goal_difference": 0.05,
    "latest_match_date": "2026-05-28",
    "is_2026_host": 0
  },
  {
    "rank": 52,
    "team_name": "Slovakia",
    "current_strength_score": 46.96,
    "recent_form_score": 53.33,
    "recent_goal_difference_score": 49.17,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.6,
    "wins": 10,
    "draws": 2,
    "losses": 8,
    "goals_for": 25,
    "goals_against": 26,
    "average_goal_difference": -0.05,
    "latest_match_date": "2026-06-01",
    "is_2026_host": 0
  },
  {
    "rank": 53,
    "team_name": "Costa Rica",
    "current_strength_score": 46.83,
    "recent_form_score": 48.33,
    "recent_goal_difference_score": 61.67,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.45,
    "wins": 7,
    "draws": 8,
    "losses": 5,
    "goals_for": 44,
    "goals_against": 30,
    "average_goal_difference": 0.7,
    "latest_match_date": "2026-06-01",
    "is_2026_host": 0
  },
  {
    "rank": 54,
    "team_name": "Colombia",
    "current_strength_score": 46.62,
    "recent_form_score": 48.33,
    "recent_goal_difference_score": 60.83,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.45,
    "wins": 8,
    "draws": 5,
    "losses": 7,
    "goals_for": 36,
    "goals_against": 23,
    "average_goal_difference": 0.65,
    "latest_match_date": "2026-06-01",
    "is_2026_host": 0
  },
  {
    "rank": 55,
    "team_name": "Poland",
    "current_strength_score": 46.29,
    "recent_form_score": 51.67,
    "recent_goal_difference_score": 50.83,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.55,
    "wins": 9,
    "draws": 4,
    "losses": 7,
    "goals_for": 31,
    "goals_against": 30,
    "average_goal_difference": 0.05,
    "latest_match_date": "2026-05-31",
    "is_2026_host": 0
  },
  {
    "rank": 56,
    "team_name": "Iraq",
    "current_strength_score": 45.88,
    "recent_form_score": 51.67,
    "recent_goal_difference_score": 49.17,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.55,
    "wins": 9,
    "draws": 4,
    "losses": 7,
    "goals_for": 20,
    "goals_against": 21,
    "average_goal_difference": -0.05,
    "latest_match_date": "2026-05-29",
    "is_2026_host": 0
  },
  {
    "rank": 57,
    "team_name": "Angola",
    "current_strength_score": 45.83,
    "recent_form_score": 50,
    "recent_goal_difference_score": 53.33,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.5,
    "wins": 7,
    "draws": 9,
    "losses": 4,
    "goals_for": 21,
    "goals_against": 17,
    "average_goal_difference": 0.2,
    "latest_match_date": "2025-12-29",
    "is_2026_host": 0
  },
  {
    "rank": 58,
    "team_name": "Ukraine",
    "current_strength_score": 45.46,
    "recent_form_score": 51.67,
    "recent_goal_difference_score": 47.5,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.55,
    "wins": 9,
    "draws": 4,
    "losses": 7,
    "goals_for": 27,
    "goals_against": 30,
    "average_goal_difference": -0.15,
    "latest_match_date": "2026-05-31",
    "is_2026_host": 0
  },
  {
    "rank": 59,
    "team_name": "Scotland",
    "current_strength_score": 44.96,
    "recent_form_score": 48.33,
    "recent_goal_difference_score": 54.17,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.45,
    "wins": 9,
    "draws": 2,
    "losses": 9,
    "goals_for": 30,
    "goals_against": 25,
    "average_goal_difference": 0.25,
    "latest_match_date": "2026-05-30",
    "is_2026_host": 0
  },
  {
    "rank": 60,
    "team_name": "United Arab Emirates",
    "current_strength_score": 44.09,
    "recent_form_score": 46.67,
    "recent_goal_difference_score": 55,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.4,
    "wins": 7,
    "draws": 7,
    "losses": 6,
    "goals_for": 29,
    "goals_against": 23,
    "average_goal_difference": 0.3,
    "latest_match_date": "2025-12-15",
    "is_2026_host": 0
  },
  {
    "rank": 61,
    "team_name": "Paraguay",
    "current_strength_score": 43.71,
    "recent_form_score": 48.33,
    "recent_goal_difference_score": 49.17,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.45,
    "wins": 8,
    "draws": 5,
    "losses": 7,
    "goals_for": 21,
    "goals_against": 22,
    "average_goal_difference": -0.05,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 62,
    "team_name": "Jordan",
    "current_strength_score": 43.67,
    "recent_form_score": 46.67,
    "recent_goal_difference_score": 53.33,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.4,
    "wins": 8,
    "draws": 4,
    "losses": 8,
    "goals_for": 33,
    "goals_against": 29,
    "average_goal_difference": 0.2,
    "latest_match_date": "2026-05-31",
    "is_2026_host": 0
  },
  {
    "rank": 63,
    "team_name": "Northern Ireland",
    "current_strength_score": 43.04,
    "recent_form_score": 46.67,
    "recent_goal_difference_score": 50.83,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.4,
    "wins": 8,
    "draws": 4,
    "losses": 8,
    "goals_for": 26,
    "goals_against": 25,
    "average_goal_difference": 0.05,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 64,
    "team_name": "Czechoslovakia",
    "current_strength_score": 42.33,
    "recent_form_score": 43.33,
    "recent_goal_difference_score": 56.67,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.3,
    "wins": 6,
    "draws": 8,
    "losses": 6,
    "goals_for": 34,
    "goals_against": 26,
    "average_goal_difference": 0.4,
    "latest_match_date": "1993-11-17",
    "is_2026_host": 0
  },
  {
    "rank": 65,
    "team_name": "Ghana",
    "current_strength_score": 41.5,
    "recent_form_score": 43.33,
    "recent_goal_difference_score": 53.33,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.3,
    "wins": 7,
    "draws": 5,
    "losses": 8,
    "goals_for": 30,
    "goals_against": 26,
    "average_goal_difference": 0.2,
    "latest_match_date": "2026-05-22",
    "is_2026_host": 0
  },
  {
    "rank": 66,
    "team_name": "El Salvador",
    "current_strength_score": 40.92,
    "recent_form_score": 45,
    "recent_goal_difference_score": 46.67,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.35,
    "wins": 8,
    "draws": 3,
    "losses": 9,
    "goals_for": 20,
    "goals_against": 24,
    "average_goal_difference": -0.2,
    "latest_match_date": "2025-11-18",
    "is_2026_host": 0
  },
  {
    "rank": 67,
    "team_name": "Saudi Arabia",
    "current_strength_score": 40.92,
    "recent_form_score": 45,
    "recent_goal_difference_score": 46.67,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.35,
    "wins": 8,
    "draws": 3,
    "losses": 9,
    "goals_for": 21,
    "goals_against": 25,
    "average_goal_difference": -0.2,
    "latest_match_date": "2026-05-30",
    "is_2026_host": 0
  },
  {
    "rank": 68,
    "team_name": "Slovenia",
    "current_strength_score": 40.92,
    "recent_form_score": 45,
    "recent_goal_difference_score": 46.67,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.35,
    "wins": 6,
    "draws": 9,
    "losses": 5,
    "goals_for": 17,
    "goals_against": 21,
    "average_goal_difference": -0.2,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 69,
    "team_name": "Uruguay",
    "current_strength_score": 40.66,
    "recent_form_score": 43.33,
    "recent_goal_difference_score": 50,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.3,
    "wins": 5,
    "draws": 11,
    "losses": 4,
    "goals_for": 17,
    "goals_against": 17,
    "average_goal_difference": 0,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 70,
    "team_name": "Serbia",
    "current_strength_score": 40.29,
    "recent_form_score": 45,
    "recent_goal_difference_score": 44.17,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.35,
    "wins": 7,
    "draws": 6,
    "losses": 7,
    "goals_for": 17,
    "goals_against": 24,
    "average_goal_difference": -0.35,
    "latest_match_date": "2026-05-31",
    "is_2026_host": 0
  },
  {
    "rank": 71,
    "team_name": "Bolivia",
    "current_strength_score": 39.67,
    "recent_form_score": 45,
    "recent_goal_difference_score": 41.67,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.35,
    "wins": 8,
    "draws": 3,
    "losses": 9,
    "goals_for": 21,
    "goals_against": 31,
    "average_goal_difference": -0.5,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 72,
    "team_name": "Bosnia and Herzegovina",
    "current_strength_score": 39.17,
    "recent_form_score": 41.67,
    "recent_goal_difference_score": 48.33,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.25,
    "wins": 6,
    "draws": 7,
    "losses": 7,
    "goals_for": 28,
    "goals_against": 30,
    "average_goal_difference": -0.1,
    "latest_match_date": "2026-05-29",
    "is_2026_host": 0
  },
  {
    "rank": 73,
    "team_name": "Israel",
    "current_strength_score": 36.42,
    "recent_form_score": 40,
    "recent_goal_difference_score": 41.67,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.2,
    "wins": 7,
    "draws": 3,
    "losses": 10,
    "goals_for": 32,
    "goals_against": 42,
    "average_goal_difference": -0.5,
    "latest_match_date": "2026-03-26",
    "is_2026_host": 0
  },
  {
    "rank": 74,
    "team_name": "Indonesia",
    "current_strength_score": 36.37,
    "recent_form_score": 38.33,
    "recent_goal_difference_score": 45.83,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.15,
    "wins": 6,
    "draws": 5,
    "losses": 9,
    "goals_for": 25,
    "goals_against": 30,
    "average_goal_difference": -0.25,
    "latest_match_date": "2026-03-30",
    "is_2026_host": 0
  },
  {
    "rank": 75,
    "team_name": "Trinidad and Tobago",
    "current_strength_score": 36.16,
    "recent_form_score": 38.33,
    "recent_goal_difference_score": 45,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.15,
    "wins": 5,
    "draws": 8,
    "losses": 7,
    "goals_for": 29,
    "goals_against": 35,
    "average_goal_difference": -0.3,
    "latest_match_date": "2026-05-30",
    "is_2026_host": 0
  },
  {
    "rank": 76,
    "team_name": "Hungary",
    "current_strength_score": 36,
    "recent_form_score": 40,
    "recent_goal_difference_score": 40,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.2,
    "wins": 6,
    "draws": 6,
    "losses": 8,
    "goals_for": 20,
    "goals_against": 32,
    "average_goal_difference": -0.6,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 77,
    "team_name": "Chile",
    "current_strength_score": 34.88,
    "recent_form_score": 36.67,
    "recent_goal_difference_score": 44.17,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.1,
    "wins": 6,
    "draws": 4,
    "losses": 10,
    "goals_for": 23,
    "goals_against": 30,
    "average_goal_difference": -0.35,
    "latest_match_date": "2026-03-30",
    "is_2026_host": 0
  },
  {
    "rank": 78,
    "team_name": "Togo",
    "current_strength_score": 34.88,
    "recent_form_score": 36.67,
    "recent_goal_difference_score": 44.17,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1.1,
    "wins": 5,
    "draws": 7,
    "losses": 8,
    "goals_for": 19,
    "goals_against": 26,
    "average_goal_difference": -0.35,
    "latest_match_date": "2025-10-13",
    "is_2026_host": 0
  },
  {
    "rank": 79,
    "team_name": "China PR",
    "current_strength_score": 31.66,
    "recent_form_score": 33.33,
    "recent_goal_difference_score": 40,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1,
    "wins": 5,
    "draws": 5,
    "losses": 10,
    "goals_for": 18,
    "goals_against": 30,
    "average_goal_difference": -0.6,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  },
  {
    "rank": 80,
    "team_name": "Iceland",
    "current_strength_score": 31.42,
    "recent_form_score": 31.67,
    "recent_goal_difference_score": 43.33,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 0.95,
    "wins": 5,
    "draws": 4,
    "losses": 11,
    "goals_for": 31,
    "goals_against": 39,
    "average_goal_difference": -0.4,
    "latest_match_date": "2026-05-31",
    "is_2026_host": 0
  },
  {
    "rank": 81,
    "team_name": "Bulgaria",
    "current_strength_score": 30.62,
    "recent_form_score": 33.33,
    "recent_goal_difference_score": 35.83,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 1,
    "wins": 5,
    "draws": 5,
    "losses": 10,
    "goals_for": 22,
    "goals_against": 39,
    "average_goal_difference": -0.85,
    "latest_match_date": "2026-06-01",
    "is_2026_host": 0
  },
  {
    "rank": 82,
    "team_name": "Qatar",
    "current_strength_score": 28.67,
    "recent_form_score": 30,
    "recent_goal_difference_score": 36.67,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 0.9,
    "wins": 4,
    "draws": 6,
    "losses": 10,
    "goals_for": 23,
    "goals_against": 39,
    "average_goal_difference": -0.8,
    "latest_match_date": "2026-05-28",
    "is_2026_host": 0
  },
  {
    "rank": 83,
    "team_name": "Cuba",
    "current_strength_score": 28.29,
    "recent_form_score": 31.67,
    "recent_goal_difference_score": 30.83,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 0.95,
    "wins": 5,
    "draws": 4,
    "losses": 11,
    "goals_for": 18,
    "goals_against": 41,
    "average_goal_difference": -1.15,
    "latest_match_date": "2025-10-11",
    "is_2026_host": 0
  },
  {
    "rank": 84,
    "team_name": "Kuwait",
    "current_strength_score": 27.58,
    "recent_form_score": 28.33,
    "recent_goal_difference_score": 36.67,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 0.85,
    "wins": 3,
    "draws": 8,
    "losses": 9,
    "goals_for": 23,
    "goals_against": 39,
    "average_goal_difference": -0.8,
    "latest_match_date": "2025-12-09",
    "is_2026_host": 0
  },
  {
    "rank": 85,
    "team_name": "North Korea",
    "current_strength_score": 27.08,
    "recent_form_score": 25,
    "recent_goal_difference_score": 43.33,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 0.75,
    "wins": 3,
    "draws": 6,
    "losses": 11,
    "goals_for": 23,
    "goals_against": 31,
    "average_goal_difference": -0.4,
    "latest_match_date": "2025-06-10",
    "is_2026_host": 0
  },
  {
    "rank": 86,
    "team_name": "Peru",
    "current_strength_score": 23.46,
    "recent_form_score": 21.67,
    "recent_goal_difference_score": 37.5,
    "host_advantage_score": 0,
    "matches_used": 20,
    "points_per_match": 0.65,
    "wins": 2,
    "draws": 7,
    "losses": 11,
    "goals_for": 10,
    "goals_against": 25,
    "average_goal_difference": -0.75,
    "latest_match_date": "2026-03-31",
    "is_2026_host": 0
  }
] satisfies CurrentStrengthTeam[];
