export type HistoricalStrengthTeam = {
  rank: number;
  team_id: string;
  team_name: string;
  team_code: string;
  confederation_code: string;
  historical_strength_score: number;
  world_cup_appearances: number;
  titles: number;
  finals_appearances: number;
  semi_final_appearances: number;
  win_rate: number;
  goals_scored: number;
  goals_conceded: number;
  best_finish_label: string;
  average_finish_position_estimate: number;
  appearances_score: number;
  titles_score: number;
  finals_score: number;
  semi_finals_score: number;
  win_rate_score: number;
};

export const historicalStrengthFormula =
  "0.30 * appearances_score + 0.25 * titles_score + 0.20 * finals_score + 0.15 * semi_finals_score + 0.10 * win_rate_score";

export const historicalStrengthTeams = [
  {
    "rank": 1,
    "team_id": "N-BRA",
    "team_name": "Brazil",
    "team_code": "BRA",
    "confederation_code": "CONMEBOL",
    "historical_strength_score": 91.86,
    "world_cup_appearances": 22,
    "titles": 5,
    "finals_appearances": 7,
    "semi_final_appearances": 11,
    "win_rate": 66.67,
    "goals_scored": 237,
    "goals_conceded": 108,
    "best_finish_label": "position 1",
    "average_finish_position_estimate": 7.41,
    "appearances_score": 100,
    "titles_score": 100,
    "finals_score": 87.5,
    "semi_finals_score": 84.62,
    "win_rate_score": 66.67
  },
  {
    "rank": 2,
    "team_id": "N-DEU",
    "team_name": "Germany",
    "team_code": "DEU",
    "confederation_code": "UEFA",
    "historical_strength_score": 88.34,
    "world_cup_appearances": 20,
    "titles": 4,
    "finals_appearances": 8,
    "semi_final_appearances": 13,
    "win_rate": 60.71,
    "goals_scored": 232,
    "goals_conceded": 130,
    "best_finish_label": "position 1",
    "average_finish_position_estimate": 6.4,
    "appearances_score": 90.91,
    "titles_score": 80,
    "finals_score": 100,
    "semi_finals_score": 100,
    "win_rate_score": 60.71
  },
  {
    "rank": 3,
    "team_id": "N-ITA",
    "team_name": "Italy",
    "team_code": "ITA",
    "confederation_code": "UEFA",
    "historical_strength_score": 74.2,
    "world_cup_appearances": 18,
    "titles": 4,
    "finals_appearances": 6,
    "semi_final_appearances": 8,
    "win_rate": 54.22,
    "goals_scored": 128,
    "goals_conceded": 77,
    "best_finish_label": "position 1",
    "average_finish_position_estimate": 12.39,
    "appearances_score": 81.82,
    "titles_score": 80,
    "finals_score": 75,
    "semi_finals_score": 61.54,
    "win_rate_score": 54.22
  },
  {
    "rank": 4,
    "team_id": "N-ARG",
    "team_name": "Argentina",
    "team_code": "ARG",
    "confederation_code": "CONMEBOL",
    "historical_strength_score": 66.81,
    "world_cup_appearances": 18,
    "titles": 3,
    "finals_appearances": 6,
    "semi_final_appearances": 6,
    "win_rate": 53.41,
    "goals_scored": 152,
    "goals_conceded": 101,
    "best_finish_label": "position 1",
    "average_finish_position_estimate": 10.28,
    "appearances_score": 81.82,
    "titles_score": 60,
    "finals_score": 75,
    "semi_finals_score": 46.15,
    "win_rate_score": 53.41
  },
  {
    "rank": 5,
    "team_id": "N-FRA",
    "team_name": "France",
    "team_code": "FRA",
    "confederation_code": "UEFA",
    "historical_strength_score": 55.24,
    "world_cup_appearances": 16,
    "titles": 2,
    "finals_appearances": 4,
    "semi_final_appearances": 7,
    "win_rate": 53.42,
    "goals_scored": 136,
    "goals_conceded": 85,
    "best_finish_label": "position 1",
    "average_finish_position_estimate": 12,
    "appearances_score": 72.73,
    "titles_score": 40,
    "finals_score": 50,
    "semi_finals_score": 53.85,
    "win_rate_score": 53.42
  },
  {
    "rank": 6,
    "team_id": "N-URY",
    "team_name": "Uruguay",
    "team_code": "URY",
    "confederation_code": "CONMEBOL",
    "historical_strength_score": 44.1,
    "world_cup_appearances": 14,
    "titles": 2,
    "finals_appearances": 2,
    "semi_final_appearances": 5,
    "win_rate": 42.37,
    "goals_scored": 89,
    "goals_conceded": 76,
    "best_finish_label": "position 1",
    "average_finish_position_estimate": 12.43,
    "appearances_score": 63.64,
    "titles_score": 40,
    "finals_score": 25,
    "semi_finals_score": 38.46,
    "win_rate_score": 42.37
  },
  {
    "rank": 7,
    "team_id": "N-ENG",
    "team_name": "England",
    "team_code": "ENG",
    "confederation_code": "UEFA",
    "historical_strength_score": 37.1,
    "world_cup_appearances": 16,
    "titles": 1,
    "finals_appearances": 1,
    "semi_final_appearances": 3,
    "win_rate": 43.24,
    "goals_scored": 104,
    "goals_conceded": 68,
    "best_finish_label": "position 1",
    "average_finish_position_estimate": 11.31,
    "appearances_score": 72.73,
    "titles_score": 20,
    "finals_score": 12.5,
    "semi_finals_score": 23.08,
    "win_rate_score": 43.24
  },
  {
    "rank": 8,
    "team_id": "N-ESP",
    "team_name": "Spain",
    "team_code": "ESP",
    "confederation_code": "UEFA",
    "historical_strength_score": 36.25,
    "world_cup_appearances": 16,
    "titles": 1,
    "finals_appearances": 1,
    "semi_final_appearances": 2,
    "win_rate": 46.27,
    "goals_scored": 108,
    "goals_conceded": 75,
    "best_finish_label": "position 1",
    "average_finish_position_estimate": 14.56,
    "appearances_score": 72.73,
    "titles_score": 20,
    "finals_score": 12.5,
    "semi_finals_score": 15.38,
    "win_rate_score": 46.27
  },
  {
    "rank": 9,
    "team_id": "N-NLD",
    "team_name": "Netherlands",
    "team_code": "NLD",
    "confederation_code": "UEFA",
    "historical_strength_score": 33.72,
    "world_cup_appearances": 11,
    "titles": 0,
    "finals_appearances": 3,
    "semi_final_appearances": 5,
    "win_rate": 54.55,
    "goals_scored": 96,
    "goals_conceded": 52,
    "best_finish_label": "position 2",
    "average_finish_position_estimate": 8.45,
    "appearances_score": 50,
    "titles_score": 0,
    "finals_score": 37.5,
    "semi_finals_score": 38.46,
    "win_rate_score": 54.55
  },
  {
    "rank": 10,
    "team_id": "N-SWE",
    "team_name": "Sweden",
    "team_code": "SWE",
    "confederation_code": "UEFA",
    "historical_strength_score": 27.21,
    "world_cup_appearances": 12,
    "titles": 0,
    "finals_appearances": 1,
    "semi_final_appearances": 4,
    "win_rate": 37.25,
    "goals_scored": 80,
    "goals_conceded": 73,
    "best_finish_label": "position 2",
    "average_finish_position_estimate": 12,
    "appearances_score": 54.55,
    "titles_score": 0,
    "finals_score": 12.5,
    "semi_finals_score": 30.77,
    "win_rate_score": 37.25
  },
  {
    "rank": 11,
    "team_id": "N-MEX",
    "team_name": "Mexico",
    "team_code": "MEX",
    "confederation_code": "CONCACAF",
    "historical_strength_score": 26.01,
    "world_cup_appearances": 17,
    "titles": 0,
    "finals_appearances": 0,
    "semi_final_appearances": 0,
    "win_rate": 28.33,
    "goals_scored": 62,
    "goals_conceded": 101,
    "best_finish_label": "quarter-finals",
    "average_finish_position_estimate": 18.82,
    "appearances_score": 77.27,
    "titles_score": 0,
    "finals_score": 0,
    "semi_finals_score": 0,
    "win_rate_score": 28.33
  },
  {
    "rank": 12,
    "team_id": "N-BEL",
    "team_name": "Belgium",
    "team_code": "BEL",
    "confederation_code": "UEFA",
    "historical_strength_score": 25.52,
    "world_cup_appearances": 14,
    "titles": 0,
    "finals_appearances": 0,
    "semi_final_appearances": 2,
    "win_rate": 41.18,
    "goals_scored": 69,
    "goals_conceded": 74,
    "best_finish_label": "position 3",
    "average_finish_position_estimate": 16.21,
    "appearances_score": 63.64,
    "titles_score": 0,
    "finals_score": 0,
    "semi_finals_score": 15.38,
    "win_rate_score": 41.18
  },
  {
    "rank": 13,
    "team_id": "N-HUN",
    "team_name": "Hungary",
    "team_code": "HUN",
    "confederation_code": "UEFA",
    "historical_strength_score": 24.27,
    "world_cup_appearances": 9,
    "titles": 0,
    "finals_appearances": 2,
    "semi_final_appearances": 2,
    "win_rate": 46.88,
    "goals_scored": 87,
    "goals_conceded": 57,
    "best_finish_label": "position 2",
    "average_finish_position_estimate": 13.78,
    "appearances_score": 40.91,
    "titles_score": 0,
    "finals_score": 25,
    "semi_finals_score": 15.38,
    "win_rate_score": 46.88
  },
  {
    "rank": 14,
    "team_id": "N-SRB",
    "team_name": "Serbia",
    "team_code": "SRB",
    "confederation_code": "UEFA",
    "historical_strength_score": 23.71,
    "world_cup_appearances": 13,
    "titles": 0,
    "finals_appearances": 0,
    "semi_final_appearances": 2,
    "win_rate": 36.73,
    "goals_scored": 71,
    "goals_conceded": 71,
    "best_finish_label": "position 4",
    "average_finish_position_estimate": 15.69,
    "appearances_score": 59.09,
    "titles_score": 0,
    "finals_score": 0,
    "semi_finals_score": 15.38,
    "win_rate_score": 36.73
  },
  {
    "rank": 15,
    "team_id": "N-CSK",
    "team_name": "Czechoslovakia",
    "team_code": "CSK",
    "confederation_code": "UEFA",
    "historical_strength_score": 21.88,
    "world_cup_appearances": 8,
    "titles": 0,
    "finals_appearances": 2,
    "semi_final_appearances": 2,
    "win_rate": 36.67,
    "goals_scored": 44,
    "goals_conceded": 45,
    "best_finish_label": "position 2",
    "average_finish_position_estimate": 14.5,
    "appearances_score": 36.36,
    "titles_score": 0,
    "finals_score": 25,
    "semi_finals_score": 15.38,
    "win_rate_score": 36.67
  },
  {
    "rank": 16,
    "team_id": "N-RUS",
    "team_name": "Russia",
    "team_code": "RUS",
    "confederation_code": "UEFA",
    "historical_strength_score": 20.38,
    "world_cup_appearances": 11,
    "titles": 0,
    "finals_appearances": 0,
    "semi_final_appearances": 1,
    "win_rate": 42.22,
    "goals_scored": 77,
    "goals_conceded": 54,
    "best_finish_label": "position 4",
    "average_finish_position_estimate": 14.55,
    "appearances_score": 50,
    "titles_score": 0,
    "finals_score": 0,
    "semi_finals_score": 7.69,
    "win_rate_score": 42.22
  },
  {
    "rank": 17,
    "team_id": "N-CHE",
    "team_name": "Switzerland",
    "team_code": "CHE",
    "confederation_code": "UEFA",
    "historical_strength_score": 19.78,
    "world_cup_appearances": 12,
    "titles": 0,
    "finals_appearances": 0,
    "semi_final_appearances": 0,
    "win_rate": 34.15,
    "goals_scored": 55,
    "goals_conceded": 73,
    "best_finish_label": "quarter-finals",
    "average_finish_position_estimate": 16.67,
    "appearances_score": 54.55,
    "titles_score": 0,
    "finals_score": 0,
    "semi_finals_score": 0,
    "win_rate_score": 34.15
  },
  {
    "rank": 18,
    "team_id": "N-POL",
    "team_name": "Poland",
    "team_code": "POL",
    "confederation_code": "UEFA",
    "historical_strength_score": 19.05,
    "world_cup_appearances": 9,
    "titles": 0,
    "finals_appearances": 0,
    "semi_final_appearances": 2,
    "win_rate": 44.74,
    "goals_scored": 49,
    "goals_conceded": 50,
    "best_finish_label": "position 3",
    "average_finish_position_estimate": 15.33,
    "appearances_score": 40.91,
    "titles_score": 0,
    "finals_score": 0,
    "semi_finals_score": 15.38,
    "win_rate_score": 44.74
  },
  {
    "rank": 19,
    "team_id": "N-USA",
    "team_name": "United States",
    "team_code": "USA",
    "confederation_code": "CONCACAF",
    "historical_strength_score": 18.59,
    "world_cup_appearances": 11,
    "titles": 0,
    "finals_appearances": 0,
    "semi_final_appearances": 1,
    "win_rate": 24.32,
    "goals_scored": 40,
    "goals_conceded": 66,
    "best_finish_label": "position 3",
    "average_finish_position_estimate": 17,
    "appearances_score": 50,
    "titles_score": 0,
    "finals_score": 0,
    "semi_finals_score": 7.69,
    "win_rate_score": 24.32
  },
  {
    "rank": 20,
    "team_id": "N-HRV",
    "team_name": "Croatia",
    "team_code": "HRV",
    "confederation_code": "UEFA",
    "historical_strength_score": 18.48,
    "world_cup_appearances": 6,
    "titles": 0,
    "finals_appearances": 1,
    "semi_final_appearances": 3,
    "win_rate": 43.33,
    "goals_scored": 43,
    "goals_conceded": 33,
    "best_finish_label": "position 2",
    "average_finish_position_estimate": 13.33,
    "appearances_score": 27.27,
    "titles_score": 0,
    "finals_score": 12.5,
    "semi_finals_score": 23.08,
    "win_rate_score": 43.33
  },
  {
    "rank": 21,
    "team_id": "N-PRT",
    "team_name": "Portugal",
    "team_code": "PRT",
    "confederation_code": "UEFA",
    "historical_strength_score": 18.07,
    "world_cup_appearances": 8,
    "titles": 0,
    "finals_appearances": 0,
    "semi_final_appearances": 2,
    "win_rate": 48.57,
    "goals_scored": 61,
    "goals_conceded": 41,
    "best_finish_label": "position 3",
    "average_finish_position_estimate": 14.88,
    "appearances_score": 36.36,
    "titles_score": 0,
    "finals_score": 0,
    "semi_finals_score": 15.38,
    "win_rate_score": 48.57
  },
  {
    "rank": 22,
    "team_id": "N-KOR",
    "team_name": "South Korea",
    "team_code": "KOR",
    "confederation_code": "AFC",
    "historical_strength_score": 18,
    "world_cup_appearances": 11,
    "titles": 0,
    "finals_appearances": 0,
    "semi_final_appearances": 1,
    "win_rate": 18.42,
    "goals_scored": 39,
    "goals_conceded": 78,
    "best_finish_label": "position 4",
    "average_finish_position_estimate": 20.73,
    "appearances_score": 50,
    "titles_score": 0,
    "finals_score": 0,
    "semi_finals_score": 7.69,
    "win_rate_score": 18.42
  },
  {
    "rank": 23,
    "team_id": "N-CHL",
    "team_name": "Chile",
    "team_code": "CHL",
    "confederation_code": "CONMEBOL",
    "historical_strength_score": 16.76,
    "world_cup_appearances": 9,
    "titles": 0,
    "finals_appearances": 0,
    "semi_final_appearances": 1,
    "win_rate": 33.33,
    "goals_scored": 40,
    "goals_conceded": 49,
    "best_finish_label": "position 3",
    "average_finish_position_estimate": 19,
    "appearances_score": 40.91,
    "titles_score": 0,
    "finals_score": 0,
    "semi_finals_score": 7.69,
    "win_rate_score": 33.33
  },
  {
    "rank": 24,
    "team_id": "N-AUT",
    "team_name": "Austria",
    "team_code": "AUT",
    "confederation_code": "UEFA",
    "historical_strength_score": 15.99,
    "world_cup_appearances": 7,
    "titles": 0,
    "finals_appearances": 0,
    "semi_final_appearances": 2,
    "win_rate": 41.38,
    "goals_scored": 43,
    "goals_conceded": 47,
    "best_finish_label": "position 3",
    "average_finish_position_estimate": 14.71,
    "appearances_score": 31.82,
    "titles_score": 0,
    "finals_score": 0,
    "semi_finals_score": 15.38,
    "win_rate_score": 41.38
  },
  {
    "rank": 25,
    "team_id": "N-PRY",
    "team_name": "Paraguay",
    "team_code": "PRY",
    "confederation_code": "CONMEBOL",
    "historical_strength_score": 13.5,
    "world_cup_appearances": 8,
    "titles": 0,
    "finals_appearances": 0,
    "semi_final_appearances": 0,
    "win_rate": 25.93,
    "goals_scored": 30,
    "goals_conceded": 38,
    "best_finish_label": "quarter-finals",
    "average_finish_position_estimate": 19,
    "appearances_score": 36.36,
    "titles_score": 0,
    "finals_score": 0,
    "semi_finals_score": 0,
    "win_rate_score": 25.93
  },
  {
    "rank": 26,
    "team_id": "N-ROU",
    "team_name": "Romania",
    "team_code": "ROU",
    "confederation_code": "UEFA",
    "historical_strength_score": 13.36,
    "world_cup_appearances": 7,
    "titles": 0,
    "finals_appearances": 0,
    "semi_final_appearances": 0,
    "win_rate": 38.1,
    "goals_scored": 30,
    "goals_conceded": 32,
    "best_finish_label": "quarter-finals",
    "average_finish_position_estimate": 17.14,
    "appearances_score": 31.82,
    "titles_score": 0,
    "finals_score": 0,
    "semi_finals_score": 0,
    "win_rate_score": 38.1
  },
  {
    "rank": 27,
    "team_id": "N-CMR",
    "team_name": "Cameroon",
    "team_code": "CMR",
    "confederation_code": "CAF",
    "historical_strength_score": 12.83,
    "world_cup_appearances": 8,
    "titles": 0,
    "finals_appearances": 0,
    "semi_final_appearances": 0,
    "win_rate": 19.23,
    "goals_scored": 22,
    "goals_conceded": 47,
    "best_finish_label": "quarter-finals",
    "average_finish_position_estimate": 22,
    "appearances_score": 36.36,
    "titles_score": 0,
    "finals_score": 0,
    "semi_finals_score": 0,
    "win_rate_score": 19.23
  },
  {
    "rank": 28,
    "team_id": "N-SCO",
    "team_name": "Scotland",
    "team_code": "SCO",
    "confederation_code": "UEFA",
    "historical_strength_score": 12.65,
    "world_cup_appearances": 8,
    "titles": 0,
    "finals_appearances": 0,
    "semi_final_appearances": 0,
    "win_rate": 17.39,
    "goals_scored": 25,
    "goals_conceded": 41,
    "best_finish_label": "group stage",
    "average_finish_position_estimate": 24,
    "appearances_score": 36.36,
    "titles_score": 0,
    "finals_score": 0,
    "semi_finals_score": 0,
    "win_rate_score": 17.39
  },
  {
    "rank": 29,
    "team_id": "N-JPN",
    "team_name": "Japan",
    "team_code": "JPN",
    "confederation_code": "AFC",
    "historical_strength_score": 12.35,
    "world_cup_appearances": 7,
    "titles": 0,
    "finals_appearances": 0,
    "semi_final_appearances": 0,
    "win_rate": 28,
    "goals_scored": 25,
    "goals_conceded": 33,
    "best_finish_label": "round of 16",
    "average_finish_position_estimate": 19.43,
    "appearances_score": 31.82,
    "titles_score": 0,
    "finals_score": 0,
    "semi_finals_score": 0,
    "win_rate_score": 28
  },
  {
    "rank": 30,
    "team_id": "N-COL",
    "team_name": "Colombia",
    "team_code": "COL",
    "confederation_code": "CONMEBOL",
    "historical_strength_score": 12.27,
    "world_cup_appearances": 6,
    "titles": 0,
    "finals_appearances": 0,
    "semi_final_appearances": 0,
    "win_rate": 40.91,
    "goals_scored": 32,
    "goals_conceded": 30,
    "best_finish_label": "quarter-finals",
    "average_finish_position_estimate": 18.67,
    "appearances_score": 27.27,
    "titles_score": 0,
    "finals_score": 0,
    "semi_finals_score": 0,
    "win_rate_score": 40.91
  }
] satisfies HistoricalStrengthTeam[];
